name: nix_infra
description: Create a private PaaS on Hetzner Cloud in minutes.
version: 0.16.0-beta
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.4.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  dartssh2: ^2.12.0
  dotenv: ^4.2.0
  http: ^1.3.0
  mcp_dart: ^0.5.3
  path: ^1.9.1
  posix: ^6.0.1
  process_run: ^0.14.2
  cli_script: ^1.0.0
  ansi_escapes: ^1.1.0
  yaml: ^3.1.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
