# https://github.com/dart-lang/setup-dart
name: Draft release

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.7.1
          flavor: release
          architecture: x64

      - name: Install dependencies
        run: dart pub get --enforce-lockfile

      # - run: dart format --output=none --set-exit-if-changed .
      # - run: dart analyze
      # - name: Run tests
      #   run: dart test

      - name: Compile nix-infra executable
        run: dart compile exe --verbosity error --target-os linux -o bin/nix-infra bin/nix_infra.dart

      - name: Compile nix-infra-cluster-mcp executable
        run: dart compile exe --verbosity error --target-os linux -o bin/nix-infra-cluster-mcp bin/nix_infra_cluster_mcp.dart

      - name: Compile nix-infra-machine-mcp executable
        run: dart compile exe --verbosity error --target-os linux -o bin/nix-infra-machine-mcp bin/nix_infra_machine_mcp.dart

      - name: Compile nix-infra-dev-mcp executable
        run: dart compile exe --verbosity error --target-os linux -o bin/nix-infra-dev-mcp bin/nix_infra_dev_mcp.dart
      
      # Export the binaries
      # https://github.com/marketplace/actions/upload-files-to-a-github-release
      - name: Upload nix-infra binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          file: bin/nix-infra
          asset_name: nix-infra
          tag: ${{ github.ref }}
          body: "This is my release text"

      - name: Upload nix-infra-cluster-mcp binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          file: bin/nix-infra-cluster-mcp
          asset_name: nix-infra-cluster-mcp
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload nix-infra-machine-mcp binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          file: bin/nix-infra-machine-mcp
          asset_name: nix-infra-machine-mcp
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload nix-infra-dev-mcp binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          file: bin/nix-infra-dev-mcp
          asset_name: nix-infra-dev-mcp
          tag: ${{ github.ref }}
          overwrite: true
